import { useEffect } from "react";
import SectionLabel from "./SectionLabel.jsx";
import { RouterLink } from "../lib/router.jsx";

/**
 * Privacy — DPDPA + GDPR-ready.
 * Plain language, no legalese for its own sake.
 */
export default function Privacy() {
  useEffect(() => { document.title = "privacy — dreamclerk"; }, []);

  return (
    <section className="section legal" id="privacy">
      <div className="wrap legal__wrap">
        <SectionLabel status="ok">$ cat /legal/privacy.md</SectionLabel>

        <h1 className="legal__title">privacy</h1>
        <p className="legal__meta">last updated · 2026-06-15 · v1.4</p>

        <p className="legal__lede">
          short version: we collect the minimum data needed to give you a career simulation, we do not sell it, and you can delete it any time. full version below.
        </p>

        <h2>$ what we collect</h2>
        <ul>
          <li><b>account data</b> — name, email, college, grad year, github handle (you give us).</li>
          <li><b>work data</b> — code submissions, pr descriptions, ai review scores, sprint velocity (generated by your use of the platform).</li>
          <li><b>device data</b> — ip, user-agent, browser locale (standard web logs, 30 days).</li>
          <li><b>payment data</b> — none until cohort 2. handled by razorpay or stripe, we never see your card number.</li>
        </ul>

        <h2>$ what we do not collect</h2>
        <ul>
          <li>no third-party tracking pixels before launch (post-launch: plausible analytics, no google analytics, no facebook pixel unless you opt in).</li>
          <li>no ad network data sales. ever.</li>
          <li>no clipboard, no keystroke capture, no keystroke timing.</li>
        </ul>

        <h2>$ how we use it</h2>
        <ul>
          <li>to run the platform (you can't ship code without code submissions).</li>
          <li>to generate your verified work certificate (it needs your prs and review scores).</li>
          <li>to email you about cohort openings, platform changes, and important security notices (you can unsubscribe from cohort and platform-change emails in one click; security notices cannot be unsubscribed from).</li>
        </ul>

        <h2>$ your rights (DPDPA, GDPR, IT act)</h2>
        <ul>
          <li><b>access</b> — email <a href="mailto:info@dreamclerk.com">info@dreamclerk.com</a> (or the legacy alias <a href="mailto:hi@dreamclerk.com">hi@dreamclerk.com</a>), we will export everything we have on you within 7 days.</li>
          <li><b>correct</b> — log in, edit your profile, hit save. or email us.</li>
          <li><b>delete</b> — log in, settings → delete account. or email us. we delete within 30 days; backups within 90 days.</li>
          <li><b>portability</b> — json export of your work data and certificate available any time.</li>
          <li><b>withdraw consent</b> — settings, or email.</li>
        </ul>

        <h2>$ retention</h2>
        <ul>
          <li>active account — kept while you are a student.</li>
          <li>inactive for 24 months — we email you twice, then we delete account data. your code submissions are kept anonymised for platform research unless you ask us to delete those too.</li>
          <li>deleted account — fully erased within 30 days; backups within 90 days.</li>
        </ul>

        <h2>$ children</h2>
        <p>the platform is for undergraduates (typically 18-22). we do not knowingly collect data from anyone under 16. if we discover we have, we delete it.</p>

        <h2>$ security</h2>
        <p>https only. passwords hashed with argon2id. secrets in vault. data at rest encrypted. security.txt at <a href="/.well-known/security.txt">/.well-known/security.txt</a>. if you find a vuln, email <a href="mailto:security@dreamclerk.com">security@dreamclerk.com</a> — we have a 90-day disclosure window and a paid bounty program once cohort 2 starts.</p>

        <h2>$ contact the dpo</h2>
        <p>anand krishnan · <a href="mailto:dpo@dreamclerk.com">dpo@dreamclerk.com</a> · chennai, india. response within 7 days.</p>

        <p className="legal__back">
          <RouterLink to="/">← back to dreamclerk</RouterLink>
        </p>
      </div>
    </section>
  );
}
