// ─── LiveActivity — continuous scroll of agent work, like a real PR feed ─
//
// Replaces the static "ticker" in the hero. The feed is generated by
// drawing from TICKER_FEED_TEMPLATES in agentsData.js, then enriching each
// entry with a randomized "moments ago" timestamp that increments while
// the component is mounted. The result: the hero never feels frozen.
//
// The ticker is also a one-click entry point to the agent modal — clicking
// any line opens the relevant agent.
//
// Performance: 6 entries visible, recycled every 30s. No network calls.

import { useEffect, useMemo, useRef, useState } from "react";
import { TICKER_FEED_TEMPLATES, AGENTS } from "../../data/agentsData.js";

const AGENT_BY_NAME = Object.fromEntries(AGENTS.map((a) => [a.name, a]));

// Build a fresh feed of `count` items from the pool, each with a random
// "moments ago" between 0 and 12 minutes. We then re-render every 30s
// with new "moments ago" values so the timestamps always feel live.
function buildFeed(count) {
  const pool = [...TICKER_FEED_TEMPLATES];
  const out = [];
  for (let i = 0; i < count && pool.length; i++) {
    const idx = Math.floor(Math.random() * pool.length);
    const entry = pool.splice(idx, 1)[0];
    out.push({ ...entry, id: `${entry.agent}-${entry.verb}-${i}`, tMin: Math.floor(Math.random() * 12) });
  }
  return out;
}

function relTime(min) {
  if (min < 1) return "now";
  if (min === 1) return "1 min ago";
  return `${min} min ago`;
}

export default function LiveActivity({ count = 6, onAgentClick }) {
  const [feed, setFeed] = useState(() => buildFeed(count));
  const ref = useRef(null);

  // Tick the timestamps every 30s. Feels live without being noisy.
  useEffect(() => {
    const t = setInterval(() => {
      setFeed((prev) =>
        prev.map((entry) => ({
          ...entry,
          tMin: Math.max(0, entry.tMin + Math.random() < 0.4 ? 1 : 0),
        }))
      );
    }, 30000);
    return () => clearInterval(t);
  }, []);

  // Sort by recency (smallest tMin first). useMemo so the list is stable
  // when nothing changed.
  const sorted = useMemo(
    () => [...feed].sort((a, b) => a.tMin - b.tMin),
    [feed]
  );

  return (
    <div className="ticker dc-ticker" ref={ref} aria-label="live pr activity">
      <div className="ticker__head">
        <span className="dot" /> live · agent activity · last 30 min
      </div>
      <ul className="ticker__list">
        {sorted.map((entry) => {
          const agent = AGENT_BY_NAME[entry.agent];
          return (
            <li
              key={entry.id}
              className="dc-ticker__row"
              role="button"
              tabIndex={0}
              onClick={() => onAgentClick?.(agent?.id)}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  onAgentClick?.(agent?.id);
                }
              }}
            >
              <span
                className="dc-ticker__dot"
                style={{ background: agent?.signatureColor || "var(--ink)" }}
                aria-hidden="true"
              />
              <span className="user">{entry.agent.toLowerCase()}</span>
              <span className="at">@</span>
              <b>{entry.object.split(" ")[0]}</b>
              <span className="dc-ticker__verb">{entry.verb}</span>
              <span className="dc-ticker__obj">
                {entry.object.replace(/^[^ ]+\s/, "")}
              </span>
              <span className="dc-ticker__time">{relTime(entry.tMin)}</span>
            </li>
          );
        })}
      </ul>
    </div>
  );
}